### ISSUE TITLE
[docker]  Make coffea-casa and coffea-casa-analysis Docker images more generic for deployment in other places (e.g. FNAL)

### ISSUE THREAD

**Issue by oshadura** [CoffeaTeam/coffea-casa#108]
Previous discussion: https://github.com/CoffeaTeam/coffea-casa/issues/24

**Comment by clundst** [comment]
Are you talking about the start page or ...?  which images?

**Comment by oshadura** [comment]
@clundst we will need to prepare images to be deployed in coffea-casa FNAL, so we will need to remove UNL HTCondor configuration files (to make actually Condor settings configurable) and maybe to think about a case we will have schedular running in K8s as well as a part of coffea-casa?

**Comment by oshadura** [comment]
@mapsacosta @holzman, we (with @clundst ) believe that coffea-casa image (https://github.com/CoffeaTeam/coffea-casa/tree/master/docker/coffea-casa) is already doesn't have any hardcoded UNL settings including HTCondor.

For https://github.com/CoffeaTeam/coffea-casa/tree/master/docker/coffea-casa-analysis we will develop probably a solution that will allow to overwrite HTCondor settings: see more here https://github.com/CoffeaTeam/coffea-casa/issues/172
