### ISSUE TITLE
Change from 'jovyan' to 'cms-jovyan' needs to be applied to the start.sh script

### ISSUE THREAD

**Issue by mapsacosta** [CoffeaTeam/coffea-casa#109]
Hi CoffeaCasa team,

I am trying to deploy the coffea-casa Docker image in our Kubernetes (OKD4 cluster) over at FNAL. 

Jupyter developers designed this 'placeholder' jovyan user with the idea of giving a configurable path to possibly creating local system users.

Long story short, I was able to deploy notebooks running as the logged user's userame instead of jovyan, but this is not possible for the coffea-casa notebooks if the start shell scripts are not ported correctly to this new jovyan-cms user. I would suggest searching and replacing `jovyan` with `cms-jovyan` on the script at `coffea-casa/blob/master/docker/coffea-casa/start.sh` and  then we can go from there

**Comment by mapsacosta** [comment]
I’m currently testing a patch for this, will open a PR soon

**Comment by oshadura** [comment]
@mapsacosta Thank you so much for reporting! and please if you need any help let me know, I probably missed it while testing cms-jovyan user... In fact this week I will work on cleaning up all UNL related files such as Conder settings and etc, so images will be more FNAL friendly!

**Comment by mapsacosta** [comment]
You're very welcome :) @oshadura 

I just opened my pull request for your review: https://github.com/CoffeaTeam/coffea-casa/pull/110
