### ISSUE TITLE
Kubernetes Worker Has 4 Threads

### ISSUE THREAD

**Issue by mat-adamec** [CoffeaTeam/coffea-casa#114]
I noticed that the HTCondor workers have been reduced from 4 to 2 threads, but the Kubernetes worker still has 4. Is this intentional, or should it have been changed too?

**Comment by oshadura** [comment]
<img width="579" alt="Screenshot 2021-07-12 at 19 14 38" src="https://user-images.githubusercontent.com/7012420/125329138-6d3e9a80-e345-11eb-84f9-910309e67f4d.png">
