### ISSUE TITLE
image / logo and iris-hep project page

### ISSUE THREAD

**Issue by cranmer** [CoffeaTeam/coffea-casa#115]
Hi, Coffee-casa has a project page on the IRIS-HEP webpage, but it doesn't have a logo or image.
See:
https://iris-hep.org/as.html

Would it make sense to use the image here?
https://cmsaf-jh.unl.edu/hub/login

**Comment by cranmer** [comment]
also noted that the project page points to 
https://github.com/CoffeaTeam/coffea-casa-config 

which seems to be a private repo b/c it gives a 404.

**Comment by oshadura** [comment]
Hi @cranmer! We are designing our logo (we have only drafts but I think it will ready over weekend). Sorry for the inconvenience!

https://github.com/CoffeaTeam/coffea-casa-config is a private repository with `coffea-casa` Helm charts including deployed secrets, I will remove it from list and replace with a Helm chart repo link.

**Comment by oshadura** [comment]
partually fixed in https://github.com/iris-hep/iris-hep.github.io-source/pull/751
