### ISSUE TITLE
Add a tech support link everywhere (coffea-casa login page, docs, tutorials)

### ISSUE THREAD

**Issue by oshadura** [CoffeaTeam/coffea-casa#131]
Link: https://github.com/CoffeaTeam/coffea-casa/discussions/categories/unl-tech-support

**Comment by AdvaitDhingra** [comment]
@oshadura I've made PRs for this issue, but what I don't know is how to add it to the login page. How can this be done?

**Comment by oshadura** [comment]
hi @AdvaitDhingra! in fact it is a bit more complex task, I will try to understand how to do this in easiest way and ping you here.

**Comment by AdvaitDhingra** [comment]
Hi @oshadura any update?
