### ISSUE TITLE
Helm charts: Missing CRD definition: IngressRouteTCP

### ISSUE THREAD

**Issue by holzman** [CoffeaTeam/coffea-casa#143]
The chart is missing a definition for the `IngressRouteTCP` CRD. 

`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "IngressRouteTCP" in version "traefik.containo.us/v1alpha1"`

**Comment by oshadura** [comment]
@jthiltges could you take a look please?

**Comment by oshadura** [comment]
@holzman thanks for reporting! I believe this was resolved in current version of chart.
