### ISSUE TITLE
Total HTCondor integration overhaul needed

### ISSUE THREAD

**Issue by clundst** [CoffeaTeam/coffea-casa#160]
Currently  I think the jobs are leveraging the GSI auth between T3, red-condor and the workers in order to satisfy security settings.  What I (Carl) have not been able to do is a) get jobs to move from the condor pod to the red-condor schedd and b) remove the GSI spaghetti from job migration.  

This shows up in the analysis pod as a fat config that contains all the UNL specific stuff needed for the worker to do the needful.

What I need is the condor container in the pod to talk to red-condor (or generic collector/negotiator) with only token/pass and then the notebook container needs to submit to the condor container and have the jobs navigate the K8s maze. 

My first stumbling block is that submitting a generic condor job from the CLI in the notebook container no longer functions and I don't know why.  

This all needs brain power.

==-==
Carl

**Comment by clundst** [comment]
I worked some on this as well and finally hit a networking wall as the coffea-casa schedd could not get jobs sent to the workers to route back for file transfers etc.  I attempted some traefik port magic that failed, or isn't quite complete.  I'm getting closer as I understand, now, how to get rid of the GSI goop and run on pure tokens.

**Comment by oshadura** [comment]
@clundst is it still valid issue?

**Comment by clundst** [comment]
With the upgrade to condor 10 most of this is solved except the k8s native scheduler.  I'll open a new issue when it rears its head again.
