### ISSUE TITLE
Develop a subclass of HTCondorCluster

### ISSUE THREAD

**Issue by bbockelm** [CoffeaTeam/coffea-casa#17]
We currently have a number of complex defaults that need to be used in order for HTCondorCluster to be usable on JupyterHub.

Instead of exposing these all to the user, we should have a small python module (`CoffeaCasaCluster` perhaps?) that does this all for us.

**Comment by oshadura** [comment]
`CoffeaCasaCluster` module lives for now in https://github.com/CoffeaTeam/coffea-casa
