### ISSUE TITLE
Take core, memory, and (maybe) disk information from ClassAd

### ISSUE THREAD

**Issue by bbockelm** [CoffeaTeam/coffea-casa#19]
We are currently hardcoding the core and memory values in the launching script:

https://github.com/CoffeaTeam/coffea-casa/blob/master/docker/coffea-casa-analysis/prepare-env.sh#L59

We should instead take this information from the ClassAd.

**Comment by oshadura** [comment]
Fixed in https://github.com/CoffeaTeam/coffea-casa/commit/a43f1412bb4f1652de93f2e70823099b60a79b51
