### ISSUE TITLE
Utilize available tokens

### ISSUE THREAD

**Issue by bbockelm** [CoffeaTeam/coffea-casa#2]
The jupyterhub config should now automatically produce secrets for the user:

https://github.com/clundst/jhub/blob/master/files/hub/jupyterhub_config.py#L288-L293

- These are all going to be in the directory `/etc/cmsaf-secrets` at container startup.  They won't, of course, exist at build time.
- The `BEARER_TOKEN_FILE` environment variable is going to be set to `/etc/cmsaf-secrets/bearer_token`, matching what's expected in the `XrdCl` plugin.
- `/etc/cmsaf-secrets/condor_token` is a condor IDTOKEN useful for submitting to t3.
- `/etc/cmsaf-secrets/ca.key` is a CA private key useful for Dask
- `/etc/cmsaf-secrets/ca.pem` is a CA public key useful for Dask
- `/etc/cmsaf-secrets/hostcert.pem` is a host certificate and private key useful for the Dask scheduler.
- `/etc/cmsaf-secrets/usercert.pem` is a user certificate and private key useful for the Dask workers.

NOTE that the condor IDTOKEN must be moved to the proper directory (`~/.condor/tokens.d` by default -- can be overridden in the condor config via `SEC_TOKENS_DIRECTORY`) prior to it being discovered and used by HTCondor tools.

We need to adjust the Dask startup and the HTCondor config to leverage these secrets.

**Comment by bbockelm** [comment]
@oshadura - is this fully complete?  Do we have TLS working?

**Comment by oshadura** [comment]
Testing and still doesnt work: https://gist.github.com/oshadura/7f87c76e181c9309895d1e86c10a94c0 I will try to see if it work for local cluster.

**Comment by bbockelm** [comment]
Looks like the client is trying TLS but the scheduler is not.  Maybe add a `tls://` prefix to the `external_address`?

**Comment by oshadura** [comment]
Resolved in Docker image coffea-casa 0.1.40 and up
