### ISSUE TITLE
Only wait until port information is available

### ISSUE THREAD

**Issue by bbockelm** [CoffeaTeam/coffea-casa#20]
See this for example:

https://github.com/JoshKarpel/dask-at-chtc/blob/master/docker/worker/entrypoint.sh#L11-L18

**Comment by oshadura** [comment]
Update: it is https://github.com/JoshKarpel/dask-chtc/blob/master/dask_chtc/entrypoint.sh

**Comment by oshadura** [comment]
Fixed in https://github.com/CoffeaTeam/coffea-casa/pull/25

To be checked:
- [ ] Test in CMSAF environment
