### ISSUE TITLE
Use job_extra instead of Stream_Output/Stream_Error patch

### ISSUE THREAD

**Issue by matyasselmeci** [CoffeaTeam/coffea-casa#21]
You should be able to replace https://github.com/CoffeaTeam/coffea-casa/blob/master/docker/coffea-casa/patches/dask_jobqueue-bbockelman.patch with adding `"Stream_Output": False, "Stream_Error": False` to the `job_extra` argument when constructing the HTCondorCluster.

**Comment by oshadura** [comment]
Tested in `coffea-casa 0.2.18` and `coffea-casa-analysis 0.2.18`
