### ISSUE TITLE
Deploy a new k8s cluster @ UNL

### ISSUE THREAD

**Issue by oshadura** [CoffeaTeam/coffea-casa#220]
Idea is to get deployed recently bought hardware as a part of k8s cluster that could be used for providing computing and storage resources for coffea-casa AF @ UNL

**Comment by bbockelm** [comment]
Current status:
- Management nodes (old hardware) not booting/kickstarting right under CentOS Stream 8.  Deciding on what to do next.
- Network configuration is planned out.
- New hardware installed with CentOS Stream 8 and on the network.

Goal for next two weeks:
- Possibly to get a minimally functioning k8s cluster (spin up "hello world" pod, but not much else).

**Comment by kenbloom** [comment]
@gattebury says we will do this in the week of January 10.

**Comment by oshadura** [comment]
New hardware was deployed and the new k8s cluster is fully functional.
