### ISSUE TITLE
Deploy monitoring for coffea-casa @ UNL: prometheus/elasticsearch instances

### ISSUE THREAD

**Issue by oshadura** [CoffeaTeam/coffea-casa#223]
Interesting metrics to add:

- Jupyterhub-related metrics: https://jupyterhub.readthedocs.io/en/stable/reference/metrics.html
- Per user Dask-related metrics https://docs.dask.org/en/stable/how-to/setup-prometheus.html
- Per user custom metrics

See more in Durbar's presentation (IRIS-HEP summer student final report): https://indico.cern.ch/event/1195270/#2-durbar-chakraborty-metrics-t

**Comment by bbockelm** [comment]
Suggested config:

https://github.com/CHTC/tiger-cluster-config/tree/master/cluster/common/prometheus

Can go into either old or new k8s instance; will need some modest customization (see: files ending in `-patch.yaml`, `expose` directory for CILogon proxy).  Mostly verbatim copies of upstream prometheus distribution for k8s.

Goal for next two weeks:
- John will read through and do first attempt to copy configs into cluster.

**Comment by kenbloom** [comment]
@jthiltges hopes for progress by January 21.

**Comment by oshadura** [comment]
@bbockelm can I ask to gave an access to https://github.com/CHTC/tiger-cluster-config repo please? thanks!

**Comment by bbockelm** [comment]
Done!

**Comment by kaimi2007** [comment]
Thank you!

**Comment by oshadura** [comment]
@Sam6734 picked up this task and we have now a publicly available instance at https://prometheus.monitoring.flatiron.hollandhpc.org with JH and Dask related metrics
