### ISSUE TITLE
Dockerfile.cc-ubuntu-skyhook arguments

### ISSUE THREAD

**Issue by fengpinghu** [CoffeaTeam/coffea-casa#284]
It appears setting some of the environment variables in this docker file is not working. My suspect is that it can not overwrite a environment from base image(I have not yet find a reference to confirm this).  So we should remove these because they are misleading and have no effect.  We could pass the environment variable via the helm chart instead of passing them at image build time.
Examples:
ARG WORKER_IMAGE="${HUB}/${PROJECT}/cc-analysis-ubuntu"
ENV WORKER_IMAGE=$WORKER_IMAGE

**Comment by oshadura** [comment]
We deleted skyhook images from the repository, so the issue is not valid anymore.

Separately, I am adding the issue to move the config files in the helm charts: https://github.com/CoffeaTeam/coffea-casa/issues/407
