### ISSUE TITLE
Possibly merge UNL and UChicago sections in the documentation

### ISSUE THREAD

**Issue by mat-adamec** [CoffeaTeam/coffea-casa#294]
There is a significant overlap between the UNL and UChicago sections within the documentation. This makes it more annoying to do routine updates of those sections because we have to port over the wording into both (and ensure we replace every instance of "T2 Nebraska" with "UChicago"). I recently proposed a merger of the two UNL sections (99f18cf4037b4281f4910f8573f7c7ec136fa269), and I think it would be good to merge these two sections too.

This would just require another entry in the "Access" section for UChicago, and a subsubsection within it for how to go through the UChicago registration process. It might also require some rewriting of the UChicago examples section, which is currently fairly sparse.

The only other difference is that the UChicago section has a ServiceX subsection. As far as I'm aware, ServiceX should function just as well on the CMS T2 Nebraska cluster, so that should probably be added there anyways. Does UChicago have some more sophisticated ServiceX support?

I can try to do this merger if given the go-ahead.

**Comment by oshadura** [comment]
@fengpinghu could you please check and let us know what do you think?

**Comment by mat-adamec** [comment]
As an added note, I think this was mentioned at our meeting today, but UChicago is strictly for ATLAS files, right? If so it'd be easy to edit the Access section directing people to UNL for CMS and UChicago for ATLAS.

Just for clarity, do CMS and ATLAS files require different tokens to access? I'd naively thought the UNL CMS instance should be able to handle both, but of course I've never tried accessing ATLAS files.

**Comment by fengpinghu** [comment]
> @fengpinghu could you please check and let us know what do you think?
I agree with Mat's idea. Merging the docs would make sense. It can make maintenance easier and also may help users to navigate better.  I'm copying @robrwg just in case.

**Comment by mat-adamec** [comment]
I have gone ahead with the merge as of https://github.com/CoffeaTeam/coffea-casa/pull/293. If any issues or complaints arise, feel free to reopen the issue and it can be revisited!
