### ISSUE TITLE
Can't Make json Files

### ISSUE THREAD

**Issue by mat-adamec** [CoffeaTeam/coffea-casa#315]
If you create a new file that ends in the .json extension, it is not editable and just says "root: {}" (as far as I can tell). This seems a little odd since we can make things like markdown files within coffea-casa.

**Comment by alexander-held** [comment]
The JupyterLab JSON editor is view-only, so this is all that can be shown for an empty file.

**Comment by mat-adamec** [comment]
Are there any plugins or extensions that make it *not* view-only, or is this just not possible in the JupyterLab infrastructure?
