### ISSUE TITLE
Patch to fix task retirement in distributed

### ISSUE THREAD

**Issue by bbockelm** [CoffeaTeam/coffea-casa#33]
It appears there's a relatively bad bug that causes the cluster to kill workers instead of retire them (the latter transfers all unique data off the worker).  Here's a fix / workaround that'll not work for upstream but will work for us:
```
--- a/distributed/deploy/spec.py
+++ b/distributed/deploy/spec.py
@@ -325,7 +325,8 @@ class SpecCluster(Cluster):
             to_close = set(self.workers) - set(self.worker_spec)
             if to_close:
                 if self.scheduler.status == Status.running:
-                    await self.scheduler_comm.retire_workers(workers=list(to_close))
+                    worker_names = ["htcondor--%s--" % self.workers[idx].job_id for idx in to_close]
+                    await self.scheduler_comm.retire_workers(names = worker_names)
                 tasks = [self.workers[w].close() for w in to_close if w in self.workers]
                 await asyncio.wait(tasks)
                 for task in tasks:  # for tornado gen.coroutine support
```

Upstream issue is https://github.com/dask/distributed/issues/4069

**Comment by bbockelm** [comment]
@oshadura - from the upstream bug, one thing that compounds this issue is we override the value provided by Dask for the name of the worker.  Without that, there's no programmatic way to match between jobs and logged-in workers.

Do you know why we do this?  It wasn't obvious from the git history.

**Comment by oshadura** [comment]
I think it is coming from `HTCondorCluster`?

**Comment by oshadura** [comment]
@bbockelm this one https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/htcondor.py#L71 correct?

**Comment by bbockelm** [comment]
No - what's passed to the command line is something like this: `--name 0`.  This gets overridden with the name from the ClassAd, which is different than what the cluster object is expecting.

**Comment by oshadura** [comment]
Ha, https://github.com/CoffeaTeam/coffea-casa/blob/master/docker/coffea-casa-analysis/prepare-env.sh#L53 we take it from Calss Ad exactly pregenerated from the line  I send before...

**Comment by oshadura** [comment]
Deployed in ``coffea-casa`` 0.2.23
