### ISSUE TITLE
Unreasonable disk usage for workers in k8s condor

### ISSUE THREAD

**Issue by clundst** [CoffeaTeam/coffea-casa#330]
After setting up htcondor-cc in the dev instance we can successfully run a single job IF we provide 200GB of ephemeral storage to the container running the condor worker.  Something (the worker image?) blows up the disk usage for the container (to 186GB).  Thus only a limited number of jobs can possibly be scaled out to the cluster (one per physical host).

**Comment by oshadura** [comment]
@clundst is it still a valid issue?

**Comment by clundst** [comment]
I've taken all the condor workers out of k8s.
