### ISSUE TITLE
Update cabinetry & pyhf in cc docker images

### ISSUE THREAD

**Issue by oshadura** [CoffeaTeam/coffea-casa#344]
Reported by @ekauffma

[AGC notebook ](https://github.com/iris-hep/analysis-grand-challenge.git) currently is crashing @ coffea-casa AFs with 
2022.09.14 tag, while running cell 14 line 4 `ws = cabinetry.workspace.build(config)`

Full error message:
```
/opt/conda/lib/python3.8/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.0.0)/charset_normalizer (2.0.9) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File /opt/conda/lib/python3.8/site-packages/jsonschema/validators.py:889, in RefResolver.resolve_from_url(self, url)
    888 try:
--> 889     document = self.store[url]
    890 except KeyError:

File /opt/conda/lib/python3.8/site-packages/jsonschema/_utils.py:28, in URIDict.__getitem__(self, uri)
     27 def __getitem__(self, uri):
---> 28     return self.store[self.normalize(uri)]

KeyError: 'file:///opt/conda/lib/python3.8/site-packages/pyhf/schemas/defs.json'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
File /opt/conda/lib/python3.8/urllib/request.py:1511, in FileHandler.open_local_file(self, req)
   1510 try:
-> 1511     stats = os.stat(localfile)
   1512     size = stats.st_size

FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.8/site-packages/pyhf/schemas/defs.json'
...
```
Connected to https://github.com/scikit-hep/pyhf/issues/1975

Blocker: waiting for new `cabinetry` release from @alexander-held

**Comment by alexander-held** [comment]
This is resolved by [`pyhf` 0.7.0](https://github.com/scikit-hep/pyhf/releases/tag/v0.7.0) / [`cabinetry` 0.5.0](https://github.com/scikit-hep/cabinetry/releases/tag/v0.5.0). I'll release `cabinetry` 0.5.1 with an unrelated fix in a bit, which could be used instead.

**Comment by alexander-held** [comment]
`cabinetry` v0.5.1 should be available on conda-forge in a bit, the corresponding feedstock was just merged (https://github.com/conda-forge/cabinetry-feedstock/pull/2). It is already available on PyPI as well (https://pypi.org/project/cabinetry/0.5.1/).

**Comment by matthewfeickert** [comment]
Yeah, as already pointed out the current versions in the "Coffea-casa build with coffea 0.7.18/dask 2022.5.0/condor and cheese" base image (apparently the `2022.09.14` tag) have

```python
from importlib.metadata import version

import jsonschema
import pyhf
import cabinetry

for lib in ["jsonschema", "pyhf", "cabinetry"]:
    print(f"{lib}: v{version(lib)}")

# jsonschema: v4.15.0
# pyhf: v0.6.3
# cabinetry: v0.4.1
```

so just updating `cabinetry` will pull in the updated `pyhf` version too.
