### ISSUE TITLE
Get XrdCl authz plugin into coffea-casa-analysis

### ISSUE THREAD

**Issue by bbockelm** [CoffeaTeam/coffea-casa#4]
Notice two things in testing:
- `coffea-casa-analysis` Docker image doesn't have the `xrdcl-authz-plugin` installed
- The `xcache_token` should be listed on both the condor `transfer_input_files` and `encrypt_input_files` for it to be moved.  Currently, it's only listed in `encrypt_input_files`.

Also, pyxrootd is missing in the `coffea-casa` image in the conda directories -- this prevents us from launching and using a dask worker inside `coffea-casa` itself.  Would be a nice part of the demo.

**Comment by bbockelm** [comment]
One more item - looking at the Xrootd code, it appears that it will refuse to load plugins that are newer than the installed version.

The Conda version of Xrootd is 4.11.x while the current compiled one in the Docker container is 4.12.x.  We should downgrade the tag

Looks like the oldest possible version for this plugin is 4.0.0; let's try that!

**Comment by oshadura** [comment]
Update: all issues are resolved, but currently we are building xrootd v4.12.1 from scratch due to dependency conflicts provided by conda. Issue need to be revised later while trying new releases of xrootd from conda.

**Comment by oshadura** [comment]
@bbockelm what do you think if I will add ``` xrdcl-authz-plugin ``` in conda-forge (it will significantly simplify life)?

**Comment by oshadura** [comment]
`xrdcl-authz-plugin` is installed in both images, for the conda distribution I opened: https://github.com/bbockelm/xrdcl-authz-plugin/issues/4
