### ISSUE TITLE
SSL Certificate Verification Failure

### ISSUE THREAD

**Issue by mat-adamec** [CoffeaTeam/coffea-casa#42]
Whether I run on cms data or public data, I'm getting timeout errors due to some SSL problem. I think they come from Dask (futures_executor works fine).

`OSError: Timed out trying to connect to 'tls://129.93.183.30:8786' after 10 s: Timed out trying to connect to 'tls://129.93.183.30:8786' after 10 s: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)`

Error with benchmark (public data): https://github.com/CoffeaTeam/coffea-casa-tutorials/blob/master/benchmarks/example1.ipynb
Error with analysis (cms data): https://github.com/CoffeaTeam/coffea-casa-tutorials/blob/master/analysis-casa.ipynb

**Comment by oshadura** [comment]
Did you restart server?

**Comment by oshadura** [comment]
Yup, I see that I can reproduce your problem: https://gist.github.com/oshadura/f5151c0ac257313a6c23eb03ef4ddfc3

**Comment by mat-adamec** [comment]
I'm pretty sure that I did. I just tried restarting again as a sanity check, but the error persists.

**Comment by oshadura** [comment]
I need to ask @clundst or @gattebury what is 129.93.183.30 and why we both are trying to use the same IP here?

**Comment by oshadura** [comment]
@mat-adamec do you still see this problem?

**Comment by mat-adamec** [comment]
Nope! Everything seems to be running just fine.
