### ISSUE TITLE
Investigate auto-scale

### ISSUE THREAD

**Issue by bbockelm** [CoffeaTeam/coffea-casa#5]
For the demo, we're mostly doing a fixed scale.  We should determine how the Dask scale up / scale down behavior interacts with coffea-casa

**Comment by oshadura** [comment]
Update: autoscaling is easily enabled via ```client = CoffeaCasaCluster(worker_image="coffeateam/coffea-casa-analysis:0.1.40", external_ip=host_ip, min_scale=5, max_scale=6) ``` or ``` cluster.adapt(minimum_jobs=min_scale, maximum_jobs=max_scale)```, but coffea-casa is missing large scale testing.

**Comment by oshadura** [comment]
Related issue: https://github.com/xrootd/xrootd/pull/1260

**Comment by oshadura** [comment]
Another related issue: https://github.com/dask/distributed/issues/4069

**Comment by oshadura** [comment]
@bbockelm I see sometimes (very rarely) with autoscaling coffea-casa is failing: https://gist.github.com/oshadura/7dd44b495345edb1b3622117595ad047

**Comment by oshadura** [comment]
I will close this issue since scaling is enabled by default in CMSAF.
