### ISSUE TITLE
Create sidecar container with a Dask worker

### ISSUE THREAD

**Issue by bbockelm** [CoffeaTeam/coffea-casa#6]
We should put together a minimal Dask worker sidecar that will be auto-started by KubeSpawner along with the container itself.

**Comment by oshadura** [comment]
@bbockelm can you please explain a bit more where I should plug minimal Dask worker sidecar?

**Comment by gattebury** [comment]
Random side note, here's an affinity snippet that should go in the worker sidecars to make them land on 'good' nodes whenever possible:

`    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
              - key: nettype
                operator: In
                values:
                - 10g`

**Comment by bbockelm** [comment]
Ok, some progress on this one.  It's more complicated than it looked originally because the Dask worker on HTCondor must be able to contact the Dask worker on Kubernetes directly.  For that, we're going to use the same trick with SNI in order to have Traefik route the TCP connection to the correct Kubernetes service.

So, what's needed?

1. First, [this patch](https://github.com/dask/distributed/issues/4070) prevents the Dask scheduler from resolving the hostname to an IP address.  By keeping the hostname internally, we will eventually pass it to OpenSSL which will add the SNI header correctly.  Needs to be added to the JupyterLab image.
2.  In https://github.com/CoffeaTeam/jhub/pull/21, we add a new DNS hostname for the Dask worker of the form `foo.dask-worker.coffea.casa`.  Requests to this TLS endpoint on port 8786 will be routed to port 8788 of the user's JupyterLab pod.  Needs to be merged and JupyterHub redeployed.
3.  Startup a Dask worker in a sidecar!  This is a second container in the JupyterLab pod.  See [here](https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/advanced.html#hub-extracontainers) for info on how to add an extra container alongside the JupyterLab.

For testing, I just ran `dask-worker` in a terminal from within JuypyterLab.  Here's the CLI used:

```
dask-worker \
    --tls-ca-file /etc/cmsaf-secrets/ca.pem \
    --tls-cert /etc/cmsaf-secrets/hostcert.pem \
    --tls-key /etc/cmsaf-secrets/hostcert.pem \
    --listen-address tls://0.0.0.0:8788 \
    --name kubernetes-worker \
    --contact-address tls://brian-2ebockelman-40cern-2ech.dask-worker.coffea.casa:8786 \
    tls://localhost:8786
```
