### ISSUE TITLE
Default Terminal Python is 2.7.16

### ISSUE THREAD

**Issue by mat-adamec** [CoffeaTeam/coffea-casa#61]
Using Python out of the box in the terminal gets you version 2.7.16.

```
python --version
Python 2.7.16
```

python3 is not a recognized command, either.

```
python3
bash: python3: command not found
```

A resolution for now is to use /opt/conda/bin/python:

```
/opt/conda/bin/python --version
Python 3.8.5
```

Ideal behavior (i.e., behavior I'd expect!) would probably be 3.\*.\* by default, or at least python3 as a functional command to use 3.\*.\*

**Comment by oshadura** [comment]
@mat-adamec thanks for reporting! It is fixed in https://github.com/CoffeaTeam/coffea-casa/commit/4489270ad5ce9612a927579ff0b8220946bf5e44
