### ISSUE TITLE
Add xgboost and pyhf packages

### ISSUE THREAD

**Issue by mat-adamec** [CoffeaTeam/coffea-casa#62]
I think [xgboost](https://xgboost.readthedocs.io/en/latest/python/python_intro.html) and [pyhf ](https://scikit-hep.org/pyhf/intro.html) should come as default packages. They're tools that complement coffea for machine learning and statistical fitting, respectively, and they seem to be the go-to for these purposes (the coffea team pointed me to both of them).

**Comment by oshadura** [comment]
Available from: 0.4.7

**Comment by oshadura** [comment]
@mat-adamec could you please recheck once you will have time?
