### ISSUE TITLE
How to install packages?

### ISSUE THREAD

**Issue by mat-adamec** [CoffeaTeam/coffea-casa#63]
It's currently possible to install packages in the terminal with pip through:
`
/opt/conda/bin/python -m pip install {package}`

Or with conda through:

`conda install -c conda-forge xgboost`

I don't believe that this actually installs these packages on the workers, however, which would lead to problems if they were used in the processor class.

If there is a way to get them onto the workers as well, then it should be added to the documentation.

**Comment by oshadura** [comment]
@mat-adamec I believe we have a temporary fix for this?

**Comment by mat-adamec** [comment]
The fix is in the documentation [here](https://coffea-casa.readthedocs.io/en/latest/cc_packages.html).
