### ISSUE TITLE
Integrate HTCondorCluster settings with the Dask labextension

### ISSUE THREAD

**Issue by bbockelm** [CoffeaTeam/coffea-casa#7]
The Dask labextension UI has a clever "start cluster" button.  We should fill in the labextension.yaml so this button works with our crazy HTCondorCluster settings.

**Comment by oshadura** [comment]
Depends on https://github.com/CoffeaTeam/coffea-casa/issues/17

**Comment by oshadura** [comment]
Available in CMSAF as a part of `coffea-casa 0.2.18`.

To be checked:
- [x] Test in CMSAF environment
