### ISSUE TITLE
cmsaf log-in screen button is orange on selection

### ISSUE THREAD

**Issue by mat-adamec** [CoffeaTeam/coffea-casa#76]
Title says it all. I think during the color revamp, one color was left forgotten.

(Maybe this is intentional, but it does look a little out-of-place if so!)

![image](https://user-images.githubusercontent.com/25493839/107890336-0b851c00-6ede-11eb-9362-c7fe943497ca.png)

**Comment by mat-adamec** [comment]
I also notice two other minor errors: there's an extra space after Facility in the first line ("Coffea-Casa Analysis Facility ,..."), and the third line says "please email email HCC Support."

Other than that, I think the procedures for sign-up have been made a lot clearer, so good job!

**Comment by clundst** [comment]
Should be fixed.  Modified the custom html file that is pulled in.
