### ISSUE TITLE
File Save Error

### ISSUE THREAD

**Issue by mat-adamec** [CoffeaTeam/coffea-casa#77]
I was running my analysis on the sidecar worker today, and ran into this pop-up in JupyterLab several times.

![image](https://user-images.githubusercontent.com/25493839/108003639-00eb8500-6fb9-11eb-8a59-b5a516c7b15b.png)

The first time it popped up, the analysis seemed to continue on. The second time it popped up (around 59%), it seemed to hang forever. I'm using the [analysis-casa.ipynb](https://github.com/CoffeaTeam/coffea-casa-tutorials/blob/master/analysis/analysis-casa.ipynb) file from the tutorial repository, which may be somewhat outdated.

**Comment by mat-adamec** [comment]
I ended the run when it seemed to hang at 59%, and started a run on one of the smaller examples. It continued to hang at 0%, so it seems that if this error pops up it fries your ability to run analyses until you do a server restart.

**Comment by mat-adamec** [comment]
Just confirming that this error is still persisting after all the power outage problems have been resolved, so I don't think it's related to that. I was, however, able to finish a run on my analysis despite it popping up, so the hanging problem might be separate from this error pop-up (and _that_ might have been related to the power outages).

**Comment by mat-adamec** [comment]
Another similar pop-up is this, which occasionally comes up in the middle of an analysis run:
![image](https://user-images.githubusercontent.com/25493839/108600159-27177900-735b-11eb-9cf2-eff08c3fe3a7.png)

I can at least understand what this one means, though it doesn't seem to be true. If I just hit "dismiss" and ignore it, the analysis continues to run and I can continue to do new runs afterwards without a server restart.

**Comment by oshadura** [comment]
I think this problem was resolved, please reopen this GH issue again.
