### ISSUE TITLE
Dask Dashboard Inaccessible without Sidecar

### ISSUE THREAD

**Issue by mat-adamec** [CoffeaTeam/coffea-casa#80]
If you set up Dask without using the sidecar, i.e., through:

```
cluster = CoffeaCasaCluster()
cluster.scale(jobs=30) 
client = Client(cluster)
```

Then it starts up fine and sends the message:
```
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at: tls://192.168.144.165:8786
distributed.scheduler - INFO -   dashboard at:                     :8787
distributed.scheduler - INFO - Receive client connection: Client-a10a7331-716e-11eb-8a6a-fafc12dcbab4
distributed.core - INFO - Starting established connection
```

However, the link it gives to the Dask scheduler is inaccessible. This seems bad - the dashboard gives a lot of useful info about what happens during the analysis run. Is this intentional because of some issues it'd make with the sidecar scheduler, or can it be fixed?

**Comment by oshadura** [comment]
It seems it is working in current version:
<img width="1415" alt="Screenshot 2021-04-22 at 16 27 45" src="https://user-images.githubusercontent.com/7012420/115731820-bc4ce300-a387-11eb-9428-270c68bc2a06.png">

**Comment by oshadura** [comment]
@mat-adamec could you please recheck whenever you will have time and close this issue?

**Comment by mat-adamec** [comment]
The buttons in the sidebar work, but the link to the dashboard itself doesn't.

I think this is okay. The buttons have all the same information. But it isn't necessarily intuitive to people who have used Dask with the regular scheduler dashboard before. I think this would be a good thing to put into common issues.
